# Loading Data
`Different Methods of loading and writing data using pandas`
| **Function** | **Description** |
| --- | ---|
| `read_csv` | Load delimited data from a file, URL, or file-like object; use comma as default delimiter | 
| `read_fwf ` | Read data in fixed-width column format (i.e., no delimiters)
 | 
| `read_clipboard` | Variation of read_csv that reads data from the clipboard; useful for converting tables from web

## Working with txt and csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("example.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
#Loading without headers
df=pd.read_csv('example.csv', header=None)
df

   0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [5]:
#loading with custom header
df=pd.read_csv("example.csv", names=["a", "b", "c", "d", "message"])
df

   a   b   c   d  message
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [6]:
#Suppose you wanted the message column to be the index of the returned DataFrame.
# You can either indicate you want the column at index 4 or named "message" using
# the index_col argument:
names = ["a", "b", "c", "d", "message"]
df=pd.read_csv("example.csv", names=names, index_col="message")
df

         a   b   c   d
message
message  a   b   c   d
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [7]:
# If you want to form a hierarchical index
parsed = pd.read_csv("example2.csv",index_col=["key1", "key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [8]:
result = pd.read_csv("example.txt", sep="\s+")
result

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\RC\AppData\Local\Temp\ipykernel_9588\2045930127.py:1: SyntaxWarning: invalid escape sequence '\s'
  result = pd.read_csv("example.txt", sep="\s+")

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [10]:
#Loading Data with Missing Values
result = pd.read_csv("example3.csv")
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [11]:
result = pd.read_csv("example3.csv", na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [12]:
result2 = pd.read_csv("example3.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [13]:
# Reading Data in small pieces
pd.read_csv("example.csv", nrows=2)

   a  b  c  d message
0  1  2  3  4   hello
1  5  6  7  8   world

## Working with json data

In [17]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
 {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

In [ ]:
# Python to json
import json
result=json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [ ]:
# Json to python
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [21]:
#Reading json with pandas
df=pd.read_json("example.json")
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

And there are various methods to load various types of datasets
Read the book  `WesMcKinney-Python-for-Data-Analysis-Data-Wrangling-with-pandas,NumPy,and Jupyter-OReilly`