# Data Cleaning tutorial by wesmickiney book

During the course of doing data analysis and modeling, a significant amount of time
is spent on data preparation: loading, cleaning, transforming, and rearranging. Such
tasks are often reported to take up 80% or more of an analyst’s time. Sometimes the
way that data is stored in files or databases is not in the right format for a particular
task. Many researchers choose to do ad hoc processing of data from one form to
another using a general-purpose programming language, like Python, Perl, R, or Java,
or Unix text-processing tools like sed or awk. Fortunately, pandas, along with the
built-in Python language features, provides you with a high-level, flexible, and fast set
of tools to enable you to manipulate data into the right form

In [2]:
import pandas as pd
import numpy as np

## 1. Handling Missing Data

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
# Detect Missing values
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

Handling Missing:
dropna :Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much
missing data to tolerate.
fillna: Fill in missing data with some value or using an interpolation method such as "ffill" or "bfill".
isna: Return Boolean values indicating which values are missing/NA.
notna: Negation of isna, returns True for non-NA values and False for NA values.

In [5]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
# same like above but in differ way
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data.dropna(how="all") #Passing how="all" will drop only rows that are all NA:

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Keep in mind that these functions return new objects by default and do not modify
the contents of the original object.
To drop columns in the same way, pass axis="columns":

In [19]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data[4] = np.nan
print(data)
data.dropna(axis="columns", how="all")

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0